Vagrant.configure("2")do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.hostname = "box1"
    config.vm.network "private_network", ip: "192.168.57.2"
    config.vm.synced_folder "../Synced_folder", "/home/vagrant/Synced_folder"
    config.vm.provision "file", source: "./Lab2_FileToCopy.txt", destination: "/home/vagrant/Copy_folder"

    config.vm.provider :virtualbox do |vb|
        vb.name = "box1"
        vb.customize ["modifyvm", :id, "--memory", 1024]
        vb.customize ["modifyvm", :id, "--cpus", 1]
    end
end