Vagrant.configure("2") do |config|
    
    #using list
    servers=[
        {
            :hostname => "vm1",
            :box => "ubuntu/xenial64",
            :ip => "192.168.57.3",
        },
        {
            :hostname => "vm2",
            :box => "centos/7",
            :ip => "192.168.57.4"
        },
        {
            :hostname => "vm3",
            :box => "ubuntu/xenial64",
            :ip => "192.168.57.5"
        },
        {
            :hostname => "vm4",
            :box => "centos/7",
            :ip => "192.168.57.6"
        }
    ]

    #Using each loop
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]

            node.vm.network :private_network, ip: machine[:ip]

            node.vm.provider :virtualbox do |vb|
                vb.name = machine[:hostname]
                vb.memory = "1024"
            end
        end
    end
end
