Vagrant.configure("2") do |config|

    #using list
    servers=[
        {
            :hostname => "master1",
            # :box => "bento/ubuntu-18.04",
            :ip => "192.168.57.6"
        },
        {
            :hostname => "worker1",
            # :box => "bento/ubuntu-18.04",
            :ip => "192.168.57.3"
        },
        {
            :hostname => "worker2",
            # :box => "bento/ubuntu-18.04",
            :ip => "192.168.57.4"
        },
        {
            :hostname => "worker3",
            # :box => "bento/ubuntu-18.04",
            :ip => "192.168.57.5"
        }
    ]

    # using each loop
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = "bento/ubuntu-18.04"
            # node.vm.box = "generic/centos8s"
            node.vm.hostname = machine[:hostname]
            # node.vm.provision :shell, path: "ubuntu-docker.sh"
            # node.vm.provision :shell, path: "centos-docker.sh"
            node.vm.network :private_network, ip: machine[:ip]
 
            node.vm.provider :virtualbox do |vb|
                vb.name = machine[:hostname]
                vb.memory = "1024"
            end
        end
    end
end
