Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "nfs"
    config.vm.network "private_network", ip:"192.168.57.32"

    config.vm.provider :virtualbox do |vb|
        vb.name = "nfs"
        vb.memory = "500"
        # vb.cpus = "0.5"
    end
end