Vagrant.configure("2") do |config|

    #ansible-control
    config.vm.define "ansible-control" do |node|
        node.vm.box = "ubuntu/xenial64"
        node.vm.hostname = "ansible-control"
        node.vm.network :private_network, ip:"192.168.57.2"
        node.vm.network "forwarded_port", guest: 22, host: 2201, id: "ssh"

        node.vm.provider "virtualbox" do |vb|
            vb.name = "ansible-control"
            vb.memory = "1024"
        end
    end

    #web01
    config.vm.define "web01" do |node|
        node.vm.box = "ubuntu/xenial64"
        node.vm.hostname = "web01"
        node.vm.network :private_network, ip:"192.168.57.3"
        node.vm.network "forwarded_port", guest: "22", host: "2202", id: "ssh"

        node.vm.provider "virtualbox" do |vb|
            vb.name = "web01"
            vb.memory = "1024"
        end
    end  

     #web02
     config.vm.define "web02" do |node|
        node.vm.box = "ubuntu/xenial64"
        node.vm.hostname = "web02"
        node.vm.network :private_network, ip:"192.168.57.4"
        node.vm.network "forwarded_port", guest: "22", host: "2203", id: "ssh"

        node.vm.provider "virtualbox" do |vb|
            vb.name = "web02"
            vb.memory = "1024"
        end
    end  

    #db01
    config.vm.define "db01" do |node|
        node.vm.box = "ubuntu/xenial64"
        node.vm.hostname = "db01"
        node.vm.network :private_network, ip:"192.168.57.5"
        node.vm.network "forwarded_port", guest: "22", host: "2204", id: "ssh"

        node.vm.provider "virtualbox" do |vb|
            vb.name = "db01"
            vb.memory = "1024"
        end
    end

    #loadbalancer
    config.vm.define "loadbalancer" do |node|
        node.vm.box = "ubuntu/xenial64"
        node.vm.hostname = "loadbalancer"
        node.vm.network :private_network, ip:"192.168.57.6"
        node.vm.network "forwarded_port", guest:"22", host: "2205",id: "ssh"

        node.vm.provider "virtualbox" do |vb|
            vb.name = "loadbalancer"
            vb.memory = "1024"
        end
    end
end