apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
  labels:
    app: pyapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: contd-app
        image: lerndevops/samplepyapp:v2
        ports:  
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: pyapp-svc
spec:
  type: NodePort
  selector:
    app: pyapp
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001