Vagrant.configure("2") do |config|

    #ubuntu box
    config.vm.define "vm1" do |vm1|
        vm1.vm.box = "ubuntu/xenial64"
        vm1.vm.hostname = "vm1"
        vm1.vm.network "private_network", ip:"192.168.57.3"

        vm1.vm.provider "virtualbox" do |vb|
            vb.name = "vm1"
            vb.memory = "1024"
        end
    end

    #centos box
    config.vm.define "vm2" do |vm2|
        vm2.vm.box = "centos/7"
        vm2.vm.hostname = "vm2"
        vm2.vm.network "private_network", ip:"192.168.57.4"

        vm2.vm.provider "virtualbox" do |vb|
            vb.name = "vm2"
            vb.memory = "1024"
            vb.cpus = "1"
        end
    end
end
